POST http://127.0.0.1:8000/auth/register/
###
POST http://127.0.0.1:8000/auth/login/
###
POST http://127.0.0.1:8000/auth/login/token/refresh/
###
POST http://127.0.0.1:8000/products/details/
###
PUT http://127.0.0.1:8000/products/details/2/
###
GET http://127.0.0.1:8000/products/details/
###
DELETE http://127.0.0.1:8000/products/details/20/